pub struct KeyPosition {
    pub key_code: &'static str,
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub label: &'static str,
}

pub fn qwerty_ansi() -> Vec<KeyPosition> {
    vec![
        // Row 0: Number row
        KeyPosition {
            key_code: "grave",
            x: 0.0,
            y: 0.0,
            width: 1.0,
            label: "`",
        },
        KeyPosition {
            key_code: "1",
            x: 1.0,
            y: 0.0,
            width: 1.0,
            label: "1",
        },
        KeyPosition {
            key_code: "2",
            x: 2.0,
            y: 0.0,
            width: 1.0,
            label: "2",
        },
        KeyPosition {
            key_code: "3",
            x: 3.0,
            y: 0.0,
            width: 1.0,
            label: "3",
        },
        KeyPosition {
            key_code: "4",
            x: 4.0,
            y: 0.0,
            width: 1.0,
            label: "4",
        },
        KeyPosition {
            key_code: "5",
            x: 5.0,
            y: 0.0,
            width: 1.0,
            label: "5",
        },
        KeyPosition {
            key_code: "6",
            x: 6.0,
            y: 0.0,
            width: 1.0,
            label: "6",
        },
        KeyPosition {
            key_code: "7",
            x: 7.0,
            y: 0.0,
            width: 1.0,
            label: "7",
        },
        KeyPosition {
            key_code: "8",
            x: 8.0,
            y: 0.0,
            width: 1.0,
            label: "8",
        },
        KeyPosition {
            key_code: "9",
            x: 9.0,
            y: 0.0,
            width: 1.0,
            label: "9",
        },
        KeyPosition {
            key_code: "0",
            x: 10.0,
            y: 0.0,
            width: 1.0,
            label: "0",
        },
        KeyPosition {
            key_code: "minus",
            x: 11.0,
            y: 0.0,
            width: 1.0,
            label: "-",
        },
        KeyPosition {
            key_code: "equal",
            x: 12.0,
            y: 0.0,
            width: 1.0,
            label: "=",
        },
        KeyPosition {
            key_code: "backspace",
            x: 13.0,
            y: 0.0,
            width: 2.0,
            label: "Back",
        },
        // Row 1: QWERTY row
        KeyPosition {
            key_code: "tab",
            x: 0.0,
            y: 1.0,
            width: 1.5,
            label: "Tab",
        },
        KeyPosition {
            key_code: "q",
            x: 1.5,
            y: 1.0,
            width: 1.0,
            label: "Q",
        },
        KeyPosition {
            key_code: "w",
            x: 2.5,
            y: 1.0,
            width: 1.0,
            label: "W",
        },
        KeyPosition {
            key_code: "e",
            x: 3.5,
            y: 1.0,
            width: 1.0,
            label: "E",
        },
        KeyPosition {
            key_code: "r",
            x: 4.5,
            y: 1.0,
            width: 1.0,
            label: "R",
        },
        KeyPosition {
            key_code: "t",
            x: 5.5,
            y: 1.0,
            width: 1.0,
            label: "T",
        },
        KeyPosition {
            key_code: "y",
            x: 6.5,
            y: 1.0,
            width: 1.0,
            label: "Y",
        },
        KeyPosition {
            key_code: "u",
            x: 7.5,
            y: 1.0,
            width: 1.0,
            label: "U",
        },
        KeyPosition {
            key_code: "i",
            x: 8.5,
            y: 1.0,
            width: 1.0,
            label: "I",
        },
        KeyPosition {
            key_code: "o",
            x: 9.5,
            y: 1.0,
            width: 1.0,
            label: "O",
        },
        KeyPosition {
            key_code: "p",
            x: 10.5,
            y: 1.0,
            width: 1.0,
            label: "P",
        },
        KeyPosition {
            key_code: "leftbracket",
            x: 11.5,
            y: 1.0,
            width: 1.0,
            label: "[",
        },
        KeyPosition {
            key_code: "rightbracket",
            x: 12.5,
            y: 1.0,
            width: 1.0,
            label: "]",
        },
        KeyPosition {
            key_code: "backslash",
            x: 13.5,
            y: 1.0,
            width: 1.5,
            label: "\\",
        },
        // Row 2: Home row
        KeyPosition {
            key_code: "capslock",
            x: 0.0,
            y: 2.0,
            width: 1.75,
            label: "Caps",
        },
        KeyPosition {
            key_code: "a",
            x: 1.75,
            y: 2.0,
            width: 1.0,
            label: "A",
        },
        KeyPosition {
            key_code: "s",
            x: 2.75,
            y: 2.0,
            width: 1.0,
            label: "S",
        },
        KeyPosition {
            key_code: "d",
            x: 3.75,
            y: 2.0,
            width: 1.0,
            label: "D",
        },
        KeyPosition {
            key_code: "f",
            x: 4.75,
            y: 2.0,
            width: 1.0,
            label: "F",
        },
        KeyPosition {
            key_code: "g",
            x: 5.75,
            y: 2.0,
            width: 1.0,
            label: "G",
        },
        KeyPosition {
            key_code: "h",
            x: 6.75,
            y: 2.0,
            width: 1.0,
            label: "H",
        },
        KeyPosition {
            key_code: "j",
            x: 7.75,
            y: 2.0,
            width: 1.0,
            label: "J",
        },
        KeyPosition {
            key_code: "k",
            x: 8.75,
            y: 2.0,
            width: 1.0,
            label: "K",
        },
        KeyPosition {
            key_code: "l",
            x: 9.75,
            y: 2.0,
            width: 1.0,
            label: "L",
        },
        KeyPosition {
            key_code: "semicolon",
            x: 10.75,
            y: 2.0,
            width: 1.0,
            label: ";",
        },
        KeyPosition {
            key_code: "apostrophe",
            x: 11.75,
            y: 2.0,
            width: 1.0,
            label: "'",
        },
        KeyPosition {
            key_code: "enter",
            x: 12.75,
            y: 2.0,
            width: 2.25,
            label: "Enter",
        },
        // Row 3: Bottom letter row
        KeyPosition {
            key_code: "lshift",
            x: 0.0,
            y: 3.0,
            width: 2.25,
            label: "Shift",
        },
        KeyPosition {
            key_code: "z",
            x: 2.25,
            y: 3.0,
            width: 1.0,
            label: "Z",
        },
        KeyPosition {
            key_code: "x",
            x: 3.25,
            y: 3.0,
            width: 1.0,
            label: "X",
        },
        KeyPosition {
            key_code: "c",
            x: 4.25,
            y: 3.0,
            width: 1.0,
            label: "C",
        },
        KeyPosition {
            key_code: "v",
            x: 5.25,
            y: 3.0,
            width: 1.0,
            label: "V",
        },
        KeyPosition {
            key_code: "b",
            x: 6.25,
            y: 3.0,
            width: 1.0,
            label: "B",
        },
        KeyPosition {
            key_code: "n",
            x: 7.25,
            y: 3.0,
            width: 1.0,
            label: "N",
        },
        KeyPosition {
            key_code: "m",
            x: 8.25,
            y: 3.0,
            width: 1.0,
            label: "M",
        },
        KeyPosition {
            key_code: "comma",
            x: 9.25,
            y: 3.0,
            width: 1.0,
            label: ",",
        },
        KeyPosition {
            key_code: "period",
            x: 10.25,
            y: 3.0,
            width: 1.0,
            label: ".",
        },
        KeyPosition {
            key_code: "slash",
            x: 11.25,
            y: 3.0,
            width: 1.0,
            label: "/",
        },
        KeyPosition {
            key_code: "rshift",
            x: 12.25,
            y: 3.0,
            width: 2.75,
            label: "Shift",
        },
        // Row 4: Bottom row
        KeyPosition {
            key_code: "lctrl",
            x: 0.0,
            y: 4.0,
            width: 1.25,
            label: "Ctrl",
        },
        KeyPosition {
            key_code: "lsuper",
            x: 1.25,
            y: 4.0,
            width: 1.25,
            label: "Win",
        },
        KeyPosition {
            key_code: "lalt",
            x: 2.5,
            y: 4.0,
            width: 1.25,
            label: "Alt",
        },
        KeyPosition {
            key_code: "space",
            x: 3.75,
            y: 4.0,
            width: 6.25,
            label: "",
        },
        KeyPosition {
            key_code: "ralt",
            x: 10.0,
            y: 4.0,
            width: 1.25,
            label: "Alt",
        },
        KeyPosition {
            key_code: "rsuper",
            x: 11.25,
            y: 4.0,
            width: 1.25,
            label: "Win",
        },
        KeyPosition {
            key_code: "menu",
            x: 12.5,
            y: 4.0,
            width: 1.25,
            label: "Menu",
        },
        KeyPosition {
            key_code: "rctrl",
            x: 13.75,
            y: 4.0,
            width: 1.25,
            label: "Ctrl",
        },
    ]
}
